#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/safwinator/Wallpapers/japanese_pedestrian_street_everforest.png
picom --experimental-backends -b
/home/safwinator/.config/polybar/launch.sh
xset m 1/1
xinput set-prop "pointer:Glorious Model O" "libinput Accel Speed" -0.94
nm-applet
dunst
/home/safwinator/.config/bspwm/borders 

#bspc monitor -d I II III IV V 
bspc monitor -d 1 2 3 4 5  6

#bspc config border_width        3 
#bspc config active_border_color "#d3c6aa"
#bspc config focused_border_color "#d3c6aa"
#bspc config normal_border_color "#a7c080"
#bspc config window_gap           7


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
